apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rolling-update-app
  template:
    metadata:
      labels:
        app: rolling-update-app
    spec:
      containers:
      - name: rolling-update-app
        image: us-central1-docker.pkg.dev/qwiklabs-gcp-02-a4f64ee8610b/rolling-repo
        ports:
        - containerPort: 80
